### ISSUE TITLE
Allow webpack-bundle-analyzer options gives SyntaxError error

### ISSUE THREAD

**Issue by abdulkaderptp** [nimacsoft/razzle-plugin-bundle-analyzer#2]
Using the spread operator give error while running the bundle analyzer

```
node_modules/razzle-plugin-bundle-analyzer/index.js:12
			...bundleAnalyzerOptions = {}
			                            ^

SyntaxError: `...` must be followed by an identifier in declaration contexts
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by abdulkaderptp** [comment]
This has been fixed
